@startuml LordOfRings

class LordOfRings{
    +Heroes
    +Bestias
    +void initGame()
    +void play()
    +showResults()
    +Personaje crearPersonaje()
}

class Personaje{
    -String id 
    -String name
    -Integer vidas
    -Integer ataque
    -Integer defensa
    + String getString()
    +void modificarDefensa()
}

class Battle{
    +Integer numeroTiros
    getWinner()
    getLoser()
}

class Board{
    +Heroes
    +Bestias
    +showBoard()
    +getWinner()
    +getLoser()
    +void execute()
    -executeTurn()
    +getWinner()

}

class Turn{
    +Heroes
    +Bestias
    +Board
    +Movimiento
    +void execute()
    +void executeTurn()
    +getWinner()
}

class Batallones{
    +Heroes
    +Bestias
    +getBatallonesEnCola()
    +getBatallonesEnProceso()
}
