@startuml ElSeñordelosAnillos

TheLordOfTheRings *-- Personaje

Personaje <|-- Heroes
Personaje <|-- Bestias

Heroes <|-- Elfos
Heroes <|-- Hobbits
Heroes <|-- Humanos

Bestias <|-- Orcos
Bestias <|-- Trasgos 

Personaje *-- Vida
Personaje *-- Armadura 
Personaje *-- Ataque
Personaje *-- goal
Personaje *-down- modificarDefensa
TheLordOfTheRings *-- Turn
TheLordOfTheRings *-- Board

Turn *-- Movimiento 
Board *-- Battle
Board *-- Batallones
Batallones *-- Personaje
Batallones *-- enCola
Battle o-- Winner 
Battle o-- Loser

Board <- Turn


@enduml